name: Auto Comment

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Token
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        
      - name: Comment on issue/PR
        uses: actions/github-script@v6
        with:
          'github-token': ${{ secrets.PAT_TOKEN }}
          script: |
            const userLogin = context.event_name === 'issues'
              ? context.payload.issue.user.login
              : context.payload.pull_request.user.login;

            let commentBody = `@${userLogin} Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.`;

            if (context.event_name === 'issues') {
              commentBody += `\nMeanwhile, if you want to work on this issue, please raise a PR, and we will review and merge it.`;
            }

            const issueNumber = context.event_name === 'issues'
              ? context.payload.issue.number
              : context.payload.pull_request.number;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
